### PR TITLE
Test for incorrect case insensitive mimetype check

### LINKED ISSUE #2241: Codec ignored due to case sensitive MimeType check
### Your environment.
  - Version: 3.1.24 (can be repro'd on latest webrtc `master`)

### What did you do?
Initialised a `MediaEngine` with two codecs registered `VP8` (MimeType = `video/vp8`) and `H264` (MimeType = `video/h264`). 
Called `PeerConnection.SetRemoteDescription` with an `offer` sdp which has two codecs - VP8 and H264. 
Creating the answer sdp using `PeerConnection.CreateAnswer` we get sdp which has only `H264` codec. 

### What did you expect?
Expected both VP8 and H264 codec to be present in the Answer SDP

### What happened?
Due to the case sensitive comparison done in https://github.com/pion/webrtc/blob/master/internal/fmtp/fmtp.go#L70 -- the `vp8` codec is not matched at all.

### PR DESCRIPTION
**Pull request by adityaa30**
Relates to pion/webrtc #2241

#### Reference issue
Fixes #2241

### CODE REVIEW

**Comment by Sean-Der** [comment]
@adityaa30 oh also a few `golangci-lint` issues, mind fixing those and ready to merge!

**Comment by adityaa30** [comment]
> Want to uncomment that FIXME and your tests should pass? I also added you to the Pion org so your tests will run without me manually approving. 

I removed the commented FIXME. However, the tests are not running automatically?

**Comment by Sean-Der** [comment]
@adityaa30 did you get the invite to join the pion org? Tests will not run until you accept that I believe.

**Comment by adriancable** [comment]
@adityaa30 - this looks good now. Can you please squash the commits, and then I will approve it.

**Review by adriancable — APPROVED** [review]

**Comment by adityaa30** [comment]
Thanks a lot @adriancable @Sean-Der

**Pull request merged**
