### PR TITLE
Add stargazer

### LINKED ISSUE #654: Add stargazer :)
https://starchart.cc/pion/webrtc

Check this :)

### PR DESCRIPTION
**Pull request by jinleileiking**
Resolves #654

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by backkem** [comment]
Just my 2 cents:
- When I'm looking for a library, I'm usually looking for info on how to get started ASAP. This pushes this info down.
- Featuring the stargazer so prominently feels overly vain to me and may give the wrong idea. As fun/important as popularity is, I think we should aim to inspire quality over quantity at this stage.

Maybe these concerns would be less pronounced if the graph was featured less prominently.

**Comment by Sean-Der** [comment]
I agree with @backkem 

I am all for adding Stargarzers + issues opened/closed but it should be under a dedicated `Project Status` probably in the `Community Section`

This data might be important for someone when evaluating the project, but that other info is way more important.

thanks

**Comment by jinleileiking** [comment]
I will move to community section

**Comment by jinleileiking** [comment]
@Sean-Der Please check again

**Comment by Sean-Der** [comment]
Pushed with 6a0b7020b1724dcb302ddfadab0c80fabc144c97 thanks @jinleileiking :)

**Pull request closed without merging**
