### PR TITLE
Update CI configs to v0.4.7

### PR DESCRIPTION
**Pull request by pionbot**
Update lint scripts and CI configs.

### CODE REVIEW

**Comment by Sean-Der** [comment]
I am taking this one!

**Comment by Sean-Der** [comment]
@scorpionknifes if you are interested I can't grab this for another ~18 hours if you are bored!

Otherwise will be back on it tomorrow. We are SO close to being completely done!

**Comment by Sean-Der** [comment]
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥  IT IS DONE 🔥 🔥 🔥 🔥 🔥 🔥 🔥 

Amazing work @scorpionknifes, let me push these and a job well done. I really hope you stick around and work on Pion, I have had a blast working together :)

**Comment by Sean-Der** [comment]
Will merge this up now, that fail is a flake

**Review by Sean-Der — APPROVED** [review]

**Comment by scorpionknifes** [comment]
Learnt a lot, Thanks for the experience!

**Comment by Sean-Der** [comment]
Gave you a shout out on Twitter, you really did amazing work here https://twitter.com/_pion/status/1311338710617567232

If you are interested I would love help on https://github.com/pion/webrtc/projects/18 I have had some trouble pushing it across the finish line. Or really anything with Pion that you think could be better!

**Pull request merged**
