### PR TITLE
fixed create data channel returning with "SCTP not establisched"

### LINKED ISSUE #628: CreateDataChannel returns with "SCTP not establisched" error
Creating a data channel while the sctp is not established returns with an error. 

I belive
https://github.com/pion/webrtc/blob/0c5f0e088bb1f51e20d049c95455bc3c23bb01da/peerconnection.go#L1489
should be:
```
if pc.sctpTransport != nil && pc.sctpTransport.association != nil {
```

This change fixed the issue for me.

### PR DESCRIPTION
**Pull request by masterada**
#### Reference issue
Fixes #628

### CODE REVIEW

**Comment by Sean-Der** [comment]
Nice work! Excited to see you get involved @masterada  :)

If you update your commit message we should be able to merge this, it is currently failing in our CI. You can see all the scripts/rules we run in our [.travis.yml](https://github.com/pion/webrtc/blob/master/.travis.yml)

**Comment by masterada** [comment]
@Sean-Der finnally all is green, please check. It's not easy to contribute to this repo, there are also some tests that randomly fails sometimes :(

**Comment by Sean-Der** [comment]
Hey @masterada 

The way we do locking could be better in the datachannel code (not anything you added in your PR!) 

We take/drop the lock through out functions randomly, if you are up for it would love to see this refactored/cleaned up.

**Comment by Sean-Der** [comment]
Also @masterada I am frustrated by the test failures also :/

I will work on debugging them

**Pull request merged**
