### PR TITLE
PR1199 redo: Answer with sendonly when remote is recvonly

### PR DESCRIPTION
**Pull request by cameronelliott**
This is a re-application of the commits from PR1199, as the author appears busy with other stuff.
But, it was nice of him to figure this out.

The original PR is the best place for the background:
#1199 

The short introduction from original author longsleep  is:

> When receiving a remote offer with a transceiver which is recvonly, the
> answer must not set the transceiver to a receiving mode to avoid Firefox
> from complaining and failing to set the remote description with the
> following error:  **Answer tried to set recv when offer did not set send**
> While Chrome is more forgiving and happily sets remote transceiver which
> include receive even when the offer did not request ist, this needs to
> be changed to get interop with Firefox.

### CODE REVIEW

**Comment by aler9** [comment]
Hello, i tested the patch against the test suggested by @Sean-Der here:
https://github.com/pion/webrtc/issues/717#issuecomment-730123350

and tests failed:

```
--- FAIL: TestTransceiverDirection (0.44s)
    --- PASS: TestTransceiverDirection/offer_sendrecv_answer_sendrecv (0.03s)
    --- FAIL: TestTransceiverDirection/offer_send_answer_sendrecv (0.00s)
    --- FAIL: TestTransceiverDirection/offer_recv_answer_sendrecv (0.00s)
```

My suggestion is to add the test to the PR, and edit the PR to make the test succeed.

**Comment by cameronelliott** [comment]
@aler9 Thank you for pointing this out. Okay, that's a good plan. Thanks

**Comment by Sean-Der** [comment]
@aler9 thanks for catching that :) 

@cameronelliott I will be much faster on this review. It would be huge to have this fixed, hits lots of people.

**Comment by aler9** [comment]
@cameronelliott are you working on this or do you need help? (this is on my bucket list too)

**Comment by cameronelliott** [comment]
> @cameronelliott are you working on this or do you need help? (this is on my bucket list too)

@aler9 it's really sort of lower on my list, if you want to take a shot at it please go for it! I was planning to get around to it, but it's just not a blocker for me.

**Comment by cameronelliott** [comment]
@aler9 Okay, the first test was working. I got the last of the three tests working today 2/13, how do you feel about working on the middle test?
I took a look at it, but here is the issue:
Inside of AddTransceiverFromKind(), 
it currently doesn't currently handle the case of:  RTPTransceiverDirectionSendonly
And I believe it needs to call:  pc.api.NewRTPSender(track LocalTrack), but there is not a LocalTrack handy, maybe one should be created there?

Anyway, may you want to see if you can get the middle test passing, or have @Sean-Der look at it if that makes sense.
I also added Sean's Test func into the PR.

**Comment by Sean-Der** [comment]
@cameronelliott I am totally fine with the PR not passing everything! As long as we cut issues/leave things better then we found them I am up for merging anything :) 

This isn't a breaking change and if anything will make things better then they were before.

**Comment by aler9** [comment]
@cameronelliott 

1. sendonly and sendrecv must be compatible, while recvonly and sendrecv must not, therefore it's wrong to block the first case in  rtptransceiver.go

2. the code can be simplified a lot

3. the unit test doesn't cover all possible cases

Please take a look at my branch here and feel free to take everything you need.

https://github.com/pion/webrtc/compare/master...aler9:patch-direction

**Comment by cameronelliott** [comment]
> @cameronelliott
> 
> 1. sendonly and sendrecv are compatible, while recvonly and sendrecv are not, therefore it's wrong to block the first case in  rtptransceiver.go
> 2. the code can be simplified a lot
> 3. the unit test doesn't cover all possible cases, i've rewritten it
> 
> Please take a look at my branch here and feel free to take everything you need:
> 
> [master...aler9:patch-direction](https://github.com/pion/webrtc/compare/master...aler9:patch-direction)

@aler9 

Alessandro, I spent some time reviewing the changes you made, and I do truly appreciate the things you caught & fixed in my commits, and how you did the same to the tests.

After reviewing both the quantity and amount of changes you made to both the tests and to my code to confirm to the tests prior to your improvements, I'd like to ask you to consider submitting the PR for both the tests you wrote, and the changes you made to my code.

Sure, I could take your code and apply it to my repo/branch, but without your depth of understanding, I feel
better about you doing the PR as I really don't have the depth in this area that you do. 

Is that okay with you? 
How do you feel about that?
Is there another option I should be offering?

Thanks,Cameron

**Comment by Sean-Der** [comment]
and we have a merge 🚀 thank you so much @cameronelliott and @aler9 on getting this done. Such a significant improvement.

**Pull request closed without merging**
