### PR TITLE
Fix SampleBuilder packet unref

### PR DESCRIPTION
**Pull request by at-wat**
It unexpectedly unreferenced all packets
when sequence number is decreased more than 2.

### Reference issue
Fix regression from #1269

### CODE REVIEW

**Comment by at-wat** [comment]
@Sean-Der please take a look!

**Comment by Sean-Der** [comment]
@at-wat sorry missed that :(

**Comment by at-wat** [comment]
@Sean-Der thank you!
May I create `v2` branch with cherry-pick of bug fixes to bump a patch version for v2?
I'm using this in my product and not ready to move to v3.

**Comment by Sean-Der** [comment]
@at-wat yes! I will make sure to cherry-pick any bug fixes as well :)

**Pull request merged**
