### PR TITLE
Fix mediaengine negotiation when SDPFmtpLine doesn't match

### PR DESCRIPTION
**Pull request by davidzhao**
#### Description

When the remote peer supports a codec with a SDPFmtpLine that local MediaEngine doesn't support, it blindly adds remote offered codec into the negotiated list.

This causes issues Pion peer to accept a codec that it cannot support.. For example, say we supported H264 baseline:

```
		{
			RTPCodecCapability: webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, ClockRate: 90000, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f", RTCPFeedback: videoRTCPFeedback},
			PayloadType:        102,
		}
```

but remote SDP included the following

```
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
```

The current negotiated output would include both offered codecs, even though only the latter is supported

#### Solution

The negotiation process should be using partial matches if exact matches cannot be found. When exact matches are present, they should be used exclusively.

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @davidzhao 

Yes we would fix this, thank you so much for taking this on! We have two cases I am worried about. I need to look into the answer.

* Should we match if locally we don't have fmtp value, and the remote does?
* Should we match if locally we have a fmtp value, and the remote doesn't?

Would you be interested in being added to the Pion org? I would love to have you stay involved. These are good/deep fixes and hard to find RTC devs to help :)

**Comment by davidzhao** [comment]
> * Should we match if locally we don't have fmtp value, and the remote does?
> * Should we match if locally we have a fmtp value, and the remote doesn't?

Sure, let me know. I think the existing fallback behavior is that we would match in both of these cases. I'll wait to hear from you whether we should or not.

> Would you be interested in being added to the Pion org? I would love to have you stay involved. These are good/deep fixes and hard to find RTC devs to help :)

Sure, I'd like that. Using Pion for our product and it's been fun to dig in. Would love to contribute more moving forward.

**Comment by Sean-Der** [comment]
So I *think* this will cover what you need, and not break users running older WebRTC clients.

### Match (MimeType and fmtp)
```
webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"}

a=rtpmap:96 H264/90000
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
```

### No Match (MimeType and fmtp)
```
webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"}

a=rtpmap:96 H264/90000
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=ffffff
```

### One Match (MimeType)
```
webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"}

a=rtpmap:96 H264/90000
```

### One Match (MimeType)
```
webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: ""}

a=rtpmap:96 H264/90000
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
```

**Comment by davidzhao** [comment]
Are you saying that require exact fmtp matches IF both mediaengine and media description contain FMTP, but otherwise match only MimeType? In that case it'd be easier to enforce these requirements instead of the fuzzy matching logic in my current PR.

Your first example actually would not match under that definition, I'm assuming that's a typo?

## Match (MimeType and fmtp)

```
webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"}

a=rtpmap:96 H264/90000
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
```

**Comment by Sean-Der** [comment]
> Are you saying that require exact fmtp matches IF both mediaengine and media description contain FMTP, but otherwise match only MimeType? In that case it'd be easier to enforce these requirements instead of the fuzzy matching logic in my current PR.
> 
> Your first example actually would not match under that definition, I'm assuming that's a typo?
> 
> ## Match (MimeType and fmtp)
> ```
> webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeH264, SDPFmtpLine: "level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f"}
> 
> a=rtpmap:96 H264/90000
> a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
> ```

Oh yea that was a typo! Sorry about that, makes these conversations way harder when I can't type basic stuff :)

**Comment by davidzhao** [comment]
@Sean-Der what do you think of this approach? It should satisfy the above conditions.

I've kept the prefer-exact-match scenario because it's possible (tho unlikely) one codec could've set fmtpline while the next one didn't. We would still prefer to use the one with it set.

**Comment by Sean-Der** [comment]
Merged! e5c8c659caa915041dd6dbcaacbb85fe28733820 

Fantastic work @davidzhao, I hope you stay involved :)

Feel free to tag a new version if you want! `git tag v3.0.12 && git push --tags` or you can use the GitHub web ui.

**Comment by davidzhao** [comment]
Thanks Sean!

**Pull request closed without merging**
