### PR TITLE
Added examples/data-channels-flow-control

### LINKED ISSUE #811: Add a data channel example with `bufferedAmount` control
## Summary
Add a data channel example using `bufferedAmount` and `bufferedAmountLowThreshold`.

## Motivation
There was a multiple of times pion user stumbled upon the flow control issues with data channel.  I think it is nice to have an example that demonstrates how to use `bufferedAmount` and `bufferedAmountLowThreshold`.

## Describe alternatives you've considered
Just points to some external sources.

## Additional context
https://godoc.org/github.com/pion/webrtc#DataChannel

### PR DESCRIPTION
**Pull request by enobufs**
Resolves #811

### CODE REVIEW

**Comment by enobufs** [comment]
@hugoArregui I can try whatever that makes this example easier to understand. Which part did you think it was confusing? What do you mean by "removing endpoint"?

I actually tried to localize signaling exchange in the main() (so that you wouldn't see it in the logic above). Also, avoid having separate implementation for each endpoint by having Endpoint, otherwise, it would have redundant lines in the code to have shorter code. (I am just trying to find the best approach..)

**Comment by hugoArregui** [comment]
> @hugoArregui I can try whatever that makes this example easier to understand. Which part did you think it was confusing? What do you mean by "removing endpoint"?
> 
> I actually tried to localize signaling exchange in the main() (so that you wouldn't see it in the logic above). Also, avoid having separate implementation for each endpoint by having Endpoint, otherwise, it would have redundant lines in the code, more lines in the code. (I am just trying to find the best approach..)

Maybe is not possible to avoid it, for me it was distracting to read about the Endpoint struct, I was trying to understand what and endpoint was. But I'm not saying the code is not clear, I like the implementation a lot, I just think in this particullar case it may be worth to have a objectively worse code but focus on the control flow. 

How much code are you reusing though, since you are not starting the second endpoint it seems to me there is not a lot in common. I can give it a shot myself later tonight

**Comment by enobufs** [comment]
@hugoArregui Let me flatten the code to see if it looks better then...

**Comment by hugoArregui** [comment]
@enobufs perhaps something like this: https://gist.github.com/hugoArregui/fcfba97fb5f4dc06a2497d9370c413c8

Which is objectively worst than yours btw!, I just think is more straight to the point, feel free to disagree and merge as it is thought, this is very subjective.

**Comment by enobufs** [comment]
@hugoArregui I am ok with it. Can you push the code and I can approve it. Thanks!

**Comment by hugoArregui** [comment]
There you go!

**Comment by enobufs** [comment]
Oh that was fast!  It looks much better! Approved back at you! ;)

**Comment by enobufs** [comment]
Oh.. I have to update the README to align with the new code.
An unrelated test is failing also.

**Pull request merged**
