### PR TITLE
Increase requirements for Plan-B detection

### LINKED ISSUE #2193: "valid" unified plan sdp considered as planB by pion
### Your environment.
  - Version: *v3.1.25*
  - Browser: *not relevant*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

Hi, i have a problem related to plan-b and pion.

I use pion in a bot that is connected to a webrtc gateway.

Previously this gateway didn't support unified plan, and i had no issue with connecting pion and it, but with google withdrawing support of planb from their satck, the authors reworked the gateway, and now it supports unfied plan.

What this gateway does is handle sip calls and make them available through a webrtc client.
In this scenario my "bot" is the client, and relies on pion for webrtc matters.

The signaling between the bot and the gateway  is negotiated over xmpp through a jingle session:

Here is what happens:

The gateway sends a propose to my pion bot:
```
<message xmlns="jabber:client" xml:lang="en" to="83ddc5e30d9d4908be03bd652f47d1a7@openrainbow.net" from="mp_rvcp_cce750bce746486c8f17d39b753eeab6@openrainbow.net/mediapillar">
   <propose xmlns="urn:xmpp:jingle-message:0" id="c9j6s308hpfda453sao0">
      <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio" />
      <mediapillar xmlns="urn:xmpp:janus:1">
         <callernumber>+33999981002</callernumber>
         <callId>48D8265E-62666E0C00085A20-5F7FE700_tpcc_pbx-1</callId>
      </mediapillar>
      <unifiedplan xmlns="urn:xmpp:jingle:apps:jsep:1" />
   </propose>
</message>
```
->nothing very interesting here except the ```<unifiedplan xmlns="urn:xmpp:jingle:apps:jsep:1" />```  which means that it is an unified plan session, so in Pion I create a peerConnection with ```  config.SDPSemantics = webrtc.SDPSemanticsPlanB```

Then the bot sends "proceed" jingle packet meaning he accepts the session (nothing of consequence on pion here so won't detail that more)..

Then the gateway sends its offer in a "session-initiate" packet.

```
<iq xmlns="jabber:client" xml:lang="en" to="xx" from="yy" type="set" >
   <jingle xmlns="urn:xmpp:jingle:1" action="session-initiate" initiator="mp_rvcp_cce750bce746486c8f17d39b753eeab6@openrainbow.net" responder="83ddc5e30d9d4908be03bd652f47d1a7@openrainbow.net/gomock_196210f0-bd38-4f89-ace2-1bd3b4fa37a8" sid="c9j6s308hpfda453sao0">
      <content creator="initiator" name="audio" senders="both">
         <description xmlns="urn:xmpp:jingle:apps:rtp:1" media="audio">
            <payload-type channels="1" clockrate="8000" id="8" name="PCMA" />
            <payload-type channels="1" clockrate="8000" id="0" name="PCMU" />
            <payload-type channels="1" clockrate="48000" id="96" name="opus" />
            <payload-type channels="1" clockrate="48000" id="97" name="telephone-event" />
            <payload-type channels="1" clockrate="8000" id="101" name="telephone-event" />
            <rtcp-mux />
         </description>
         <transport xmlns="urn:xmpp:jingle:transports:ice-udp:1" pwd="qYe1EBozQG1FD8EORLFzbDO72l" ufrag="uJRDCFb0">
            <fingerprint xmlns="urn:xmpp:jingle:apps:dtls:0" hash="sha-256" setup="actpass">55:20:49:E2:F0:CD:82:96:64:45:F5:F3:32:AA:44:FB:FC:C0:1B:AF:CB:D1:E9:83:3E:A0:FD:F2:FB:70:30:F2</fingerprint>
            <candidate component="1" foundation="TwJ090uYNRcf6dG0" generation="0" id="c9j6s308h" ip="5.135.97.99" network="1" port="39192" priority="2130706431" protocol="UDP" type="host" />
         </transport>
      </content>
   </jingle>
</iq>
```

Translated into SDP, this becomes:
```
v=0
o=- 1923518516 2 IN IP4 0.0.0.0
s=-
t=0 0
m=audio 1 RTP/SAVPF 8 0 96 97 101
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:uJRDCFb0
a=ice-pwd:qYe1EBozQG1FD8EORLFzbDO72l
a=ice-options:trickle
a=fingerprint:sha-256 55:20:49:E2:F0:CD:82:96:64:45:F5:F3:32:AA:44:FB:FC:C0:1B:AF:CB:D1:E9:83:3E:A0:FD:F2:FB:70:30:F2
a=setup:actpass
a=candidate:TwJ090uYNRcf6dG0 1 UDP 2130706431 5.135.97.99 39192 typ host generation 0 network-id 1 ufrag uJRDCFb0 pwd qYe1EBozQG1FD8EORLFzbDO72l
a=sendrecv
a=mid:audio
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:96 opus/48000
a=rtpmap:97 telephone-event/48000
a=rtpmap:101 telephone-event/8000
```

The bot calls pc.SetRemoteDescription with this SDP, 
and then pc.CreateAnswer()

### What did you expect?
create answer returns an answer and i can send it to the gateway.

### What happened?

createAnswer returns the following error: 
```
remote SessionDescription semantics does not match configuration: Expected UnifiedPlan, but RemoteDescription is PlanB
```
### What the problem could be...
Apparently the same sdp works on every other stacks they tested.. mostly browsers / libwebrtc based apps.
From my understanding, pion considers the sdp offer to be planB because of  the id "audio" in the line a=mid:audio ..

So  I think I have five options here:

1. would be to fork pion, to remove this test (obviously i don't want to do that)
2. would be to change the transcoding from jingle to sdp to generate a=mid:0 instead of the original a=mid:audio line..
But from my understanding this "audio" label is used in extensions to the rtp headers and by the stack to find the right transceiver/track .. and i would have issues then with the media (so i don't want to do that too)
3. would be to use another sdp semantics: stick to planB or maybe SDPSemanticsUnifiedPlanWithFallback and, having only one media, it should be compatible..
But from what I read in the roadmap, planB is planned to be removed from pion in upcoming versions
4. would be to make the people in charge of the gateway fix the SDP and encode it in pion friendly way, (or valid way ?) but I would need a good justification for that to happen (considering it works with other stacks, and they think it's a valid sdp)
I'm struggling with the draft, and cannot find a place where it forbids them to use "audio" "video" or "data" for their mid
5. or maybe they are right, and pion should accept this SDP ?

Can you help me with that ? What do you think ?

Thanks in advance

### PR DESCRIPTION
**Pull request by Sean-Der**
Increase requirements for Plan-B detection

Before a SessionDescription was assumed to be Plan-B if it contained a
MediaName of `audio` or `video`. This PR Changes that behavior.

If SDPSemantics is UnifiedPlan the SessionDescription must contain a
MediaDescription with two SSRCes to be considered a Plan-B. Before if
the MediaDescription had name of `audio` or `video` it was assumed to be
Plan-B.

If SDPSemantics is PlanB or UnifiedPlanWithFallback it maintains the
existing behavior.

Resolves #2193

### CODE REVIEW

**Comment by Sean-Der** [comment]
Not that exciting of a PR (and would love to delete this code soon).

**Comment by adriancable** [comment]
@Sean-Der - I haven't looked at the code, but I don't think this is correct:

> If SDPSemantics is UnifiedPlan the SessionDescription must contain a
> MediaDescription with two SSRCes.

The session could be video only (so only one SSRC), or not have any media tracks at all (no SSRCs). In this case we can't know what semantics whether the generator of the SDP is using. (until new tracks get added)

The contrapositive is of course the case, that a MediaDescription with two SSRCs is necessarily UnifiedPlan.

**Comment by adriancable** [comment]
@Sean-Der - great - that now seems to match what the code does. I am happy!

**Review by adriancable — APPROVED** [review]

**Comment by atoppi** [comment]
> @adriancable updated the commit message! I think it matches what you are describing. The check is actually
> 
> ```
> If SDPSemantics is UnifiedPlan the SessionDescription must contain a
> MediaDescription with two SSRCes to be considered Plan-B. Otherwise it is considered Unified Plan
> ```

@Sean-Der what about sdp with rtx ? In that case there will be two announced ssrcs (tied together with `a=ssrc-group:FID` though)

**Comment by atoppi** [comment]
never mind, I made a quick test and it also seems to successfully handle the rtx case

**Pull request merged**
