### PR TITLE
fixed bug in examples/rtp-forwarder where packet state is not properl…

### PR DESCRIPTION
**Pull request by strangesast**
fixes corrupt RTP packet issue related to memory initialization/reset in examples/rtp-forwarder that causes frames to be distorted

### CODE REVIEW

**Comment by Sean-Der** [comment]
@strangesast are you able to reproduce this reliably? 

`Unmarshal` should be safe to use like this! Possibly `Padding` isn't cleared properly? We might need a deeper fix in `pion/rtp`

**Comment by strangesast** [comment]
yes I get frames that are distorted like this with VP8 encoding.  I had tried h.264 and get a different flavor of distortion.
Screenshot 2024-11-26 at 9 33 56 AM

when testing I noticed that I could get the demo to work with TrackRemote.ReadRTP but realized that was just a convenience wrapper around the same logic

it looks like there's an issue with how rtp.Packet.PaddingSize is set by Unmarshal.  or at least that's the only value that differs between these approaches.

it's almost certainly related to [this](https://github.com/pion/webrtc/issues/2403) and [this](https://github.com/pion/rtp/pull/155#issuecomment-1455042108)

**Comment by Sean-Der** [comment]
Ok great, I think we should fix that instead. Users have been copying/using this code so we should fix it deeper.

Would you mind making the change [here](https://github.com/pion/rtp/blob/master/packet.go#L210) to zero padding size? I believe that's the issue

**Comment by strangesast** [comment]
not at all.  I've created [this pr](https://github.com/pion/rtp/pull/284) over there

**Comment by strangesast** [comment]
the PR in pion/rtp should address the issue brought up here.  thanks for the insight and help with the fix

**Pull request closed without merging**
