### PR TITLE
Moved duplicate operation to function

### PR DESCRIPTION
**Pull request by stephanrotolante**
#### Description
Nothing crazy here, I was exploring the code base and thought this would be an easy thing to refactor

Essentially I am moving some of the duplicated actions that Get/Put packet allocations from the Pool into reusable functions :)

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by ashellunts** [comment]
LGTM, @stephanrotolante can you check linter failure please?

**Comment by stephanrotolante** [comment]
@ashellunts yes, it looks like a commit lint error

Screen Shot 2022-10-31 at 11 38 54 PM

**Comment by ashellunts** [comment]
Can you fix that please? 😀

**Comment by stephanrotolante** [comment]
@ashellunts updated!

**Comment by stephanrotolante** [comment]
ok wth give me a sec

**Comment by stephanrotolante** [comment]
@ashellunts ok I believe I got it this time. And I validated the commit by running the commit lint script on my local. I didn't know when you commit you can format the message like this `git commit -m "This is the subject" -m "This is the body"`

**Comment by stephanrotolante** [comment]
@ashellunts IMO this commit lint should run on the users machine via some pre-commit  hook. I think these ci runner take to long for this super simple check

**Comment by ashellunts** [comment]
@stephanrotolante Have you used scripts from .github folder to run all checks locally?

**Comment by stephanrotolante** [comment]
@ashellunts thank u for being patient with me

**Comment by stephanrotolante** [comment]
@ashellunts I wish these workflow would run without someone having to trigger them

**Comment by stephanrotolante** [comment]
> @stephanrotolante Have you used scripts from .github folder to run all checks locally?

yes, now I am dealing with a golang linter error

**Comment by ashellunts** [comment]
> @ashellunts IMO this commit lint should run on the users machine via some pre-commit hook. I think these ci runner take to long for this super simple check
> 
> What do you think?

I have found there is a helper script to install linter checks as pre-commit/pre-push
`.github/install-hooks.sh`

**Comment by ashellunts** [comment]
> @ashellunts I wish these workflow would run without someone having to trigger them

It only happens for a first PR of a contributor, AFAIK.

**Comment by ashellunts** [comment]
> @ashellunts thank u for being patient with me

No worries at all!

**Review by ashellunts — APPROVED** [review]

**Pull request merged**
