### PR TITLE
Modify hdlr to handler for better reading

### PR DESCRIPTION
**Pull request by soolaugust**
#### Description
Codes optimization

### CODE REVIEW

**Comment by Sean-Der** [comment]
@soolaugust LGTM, anything to make code easier to read :+1: 

Can you change all `hdlr` to `handler` to be consistent, thanks.

**Comment by soolaugust** [comment]
@Sean-Der my pleasure, changes has been commit.

**Comment by soolaugust** [comment]
@Sean-Der Please review this change, All hdlr should be modified.

**Comment by Sean-Der** [comment]
Merged! Great work on your first contribution :+1:

I love iterative changes that make things just a little bit better :)

**Pull request merged**
