### PR TITLE
Avoid blocking resource release by client code.

### PR DESCRIPTION
**Pull request by bshimc**
This fixes a brain-fart in the resource management in #1520

### CODE REVIEW

**Comment by Sean-Der** [comment]
:fire:

Mind re-doing your commit message to have a `Subject+Body` you can run `bash .github/lint-commit-message.sh` to check it locally. When it goes green, will merge. thanks!

**Comment by bshimc** [comment]
Commit message fixed.  CI is detecting a race somewhere in the PeerConnection tests and it's not obvious to me how this change could have triggered it.

**Comment by Sean-Der** [comment]
@bshimc your commit is perfect! That was introduced by me, and *should* be fixed in master. I have introduced a fair amount of churn with 7edfb701e09e89258d4b3235cded99befc8058fd

But I am working on paying the debt down! I will merge this as is, thanks for fixing :)

**Comment by Sean-Der** [comment]
Merged 32c082f6ff5344a4ccf82537ea71b45bb1677669 !

**Pull request closed without merging**
