### PR TITLE
Doc changed to distinguish between two echo

### PR DESCRIPTION
**Pull request by sylba2050**
#### Description
"echo" has two meanings: a Linux command and a pre-built binary,
so change it to make it easier to identify.

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by sylba2050** [comment]
Thank you for your reply! 

> What do you think of changing the name completely?

I think that is a very good idea! 
Do you have an opinion on the new name? I suggest that `echo-server` or ` pion-echo`.
If you decide on a name, I will start working on changing the name!

**Comment by Sean-Der** [comment]
Really excited to get your contribution in! Sorry I have been so slow, work has been very busy for me this week :(

**Comment by sylba2050** [comment]
Thanks !

> What do you think of reflect

that's sounds great for me.  I'll start working on it.   
I will do my best to finish the work as soon as possible.

**Comment by sylba2050** [comment]
@Sean-Der 
My work was probably completed.
May I ask for confirmation?

**Comment by Sean-Der** [comment]
Great news your change has landed 444e0bc576cfa9307b59e3ac588fa2729f9fb115 !

@sylba2050 thank you so much for your contribution. If you find anything else that can be improved with Pion I would love to hear :) thank you for using it.

**Comment by sylba2050** [comment]
Thank you for your work!  
 I am currently developing a product that depends on this project and will continue to use it!  
I look forward to working with you.

**Pull request closed without merging**
