### PR TITLE
Update framerate using frame count and time duration

### PR DESCRIPTION
**Pull request by raphaelpereira**
Calculate video framerate using duration and frame count

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @raphaelpereira 
Sorry for dropping the ball on this. I am trying to get better at bringing down issues/PRs.

So I don't think we can do this, what if someone has a bunch of RTP Packets ahead of time and they want to write them quickly? Can we get the timing information from the RTP Packets themselves maybe?

**Comment by Sean-Der** [comment]
Hey @raphaelpereira 

Sorry we never made any progress on this :/ I should have done better getting this through. When I find the time I will work on landing this myself, thanks.

**Comment by raphaelpereira** [comment]
Hi @Sean-Der, I am studying RFC-3550 to use RTP packet synchronization features to be able to implement this correctly. As soon as I have something working here I propose another merge request. Best Regards,

**Comment by raphaelpereira** [comment]
Hi @Sean-Der, I am studying RFC-3550 to use RTP packet synchronization features to be able to implement this correctly. As soon as I have something working here I propose another merge request. Best Regards,

**Pull request closed without merging**
