### PR TITLE
updates data-channels example README.md

### PR DESCRIPTION
**Pull request by nmyk**
#### Description
The path specified for `go get` in this example is incorrect

#### Reference issue
none

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @nmyk 

Thanks for the PR! I do think we want the `/v2` though.

What version of Go are you using? I think the issue is if we don't do`/v2` it will pull in old versions of Pion.

```
sean@SeanLaptop:~$ ls ~/go/bin/data-channels
ls: cannot access '/home/sean/go/bin/data-channels': No such file or directory

sean@SeanLaptop:~$ go get github.com/pion/webrtc/v2/examples/data-channels
go: downloading github.com/pion/webrtc/v2 v2.2.16
go: found github.com/pion/webrtc/v2/examples/data-channels in github.com/pion/webrtc/v2 v2.2.16

sean@SeanLaptop:~$ ls ~/go/bin/data-channels
/home/sean/go/bin/data-channels*
sean@SeanLaptop:~
```

**Comment by nmyk** [comment]
I'm using Go version `1.14.2`. Maybe I have something configured wrong that has nothing to do with `pion`?

```
❯ go get github.com/pion/webrtc/v2/examples/data-channels                                                     (:|✔)
package github.com/pion/webrtc/v2/examples/data-channels: cannot find package "github.com/pion/webrtc/v2/examples/data-channels" in any of:
        /usr/lib/go-1.14/src/github.com/pion/webrtc/v2/examples/data-channels (from $GOROOT)
        /home/nmykins/go/src/github.com/pion/webrtc/v2/examples/data-channels (from $GOPATH)
```

But when I remove the `/v2` it finds the example just fine.

```
❯ go get -v github.com/pion/webrtc/examples/data-channels                                                     (:|✔)
github.com/pion/datachannel (download)
github.com/pion/logging (download)
github.com/pion/sctp (download)
github.com/pion/dtls (download)
github.com/pion/transport (download)
get "golang.org/x/crypto/cryptobyte": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto/cryptobyte?go-get=1
get "golang.org/x/crypto/cryptobyte": verifying non-authoritative meta tag
golang.org/x/crypto (download)
get "golang.org/x/crypto/curve25519": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto/curve25519?go-get=1
get "golang.org/x/crypto/curve25519": verifying non-authoritative meta tag
github.com/pion/ice (download)
github.com/pion/mdns (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
github.com/pion/stun (download)
github.com/pion/turn (download)
github.com/pion/rtcp (download)
github.com/pion/rtp (download)
github.com/pion/sdp (download)
github.com/pion/srtp (download)
golang.org/x/sys/internal/unsafeheader
golang.org/x/xerrors/internal
golang.org/x/net/internal/iana
golang.org/x/crypto/cryptobyte/asn1
github.com/pion/dtls/pkg/crypto/ccm
github.com/pion/stun/internal/hmac
github.com/pion/transport/deadline
github.com/pion/dtls/internal/closer
github.com/pion/webrtc/internal/util
golang.org/x/sys/unix
github.com/pion/transport/replaydetector
github.com/pion/rtp
github.com/pkg/errors
github.com/pion/logging
github.com/pion/webrtc/pkg/rtcerr
golang.org/x/net/bpf
golang.org/x/xerrors
github.com/pion/rtp/codecs
golang.org/x/net/dns/dnsmessage
golang.org/x/crypto/curve25519
github.com/pion/rtcp
github.com/pion/sdp
github.com/pion/dtls/internal/net/connctx
golang.org/x/crypto/cryptobyte
github.com/pion/dtls/pkg/crypto/fingerprint
github.com/pion/transport/packetio
github.com/pion/stun
github.com/pion/turn/internal/ipnet
github.com/pion/webrtc/examples/internal/signal
github.com/pion/transport/vnet
github.com/pion/sctp
github.com/pion/webrtc/pkg/media
github.com/pion/dtls/internal/net/udp
github.com/pion/dtls
github.com/pion/srtp
github.com/pion/turn/internal/proto
github.com/pion/turn/internal/client
github.com/pion/turn/internal/allocation
github.com/pion/turn/internal/server
golang.org/x/net/internal/socket
github.com/pion/datachannel
github.com/pion/turn
golang.org/x/net/ipv4
github.com/pion/mdns
github.com/pion/ice
github.com/pion/webrtc/internal/mux
github.com/pion/webrtc
github.com/pion/webrtc/examples/data-channels
```

I am not sure if the version of `pion` downloaded is the most recent - so you might still be right about that.

**Comment by Sean-Der** [comment]
Do you have `GO111MODULE=off` by chance?

I am using `go version go1.14.4 linux/amd64` locally that I got directly from `golang.org` (not Debian)

**Comment by Sean-Der** [comment]
Hey @nmyk 

No rush, but did that help?

thanks

**Comment by nmyk** [comment]
Hey! I did not have `GO111MODULE=off` (it was unset). Changing it didn't seem to affect anything. I'm actually surprised that you got it to work with the `v2` path as that path doesn't seem to exist anywhere in this repo! (I have the `go get` documentation open in another tab to see if I'm just completely missing something about how go modules work lol - it's a relatively new language for me 👀 )

**Comment by Sean-Der** [comment]
@nmyk Ah yea that is the issue do `export GO111MODULE=on` and it should work! I just spun up a docker container and this works

```
docker run -it golang /bin/bash
export GO111MODULE=on
go get -u github.com/pion/webrtc/v2/examples/data-channels
```

We should update the docs to mention that! If you are up for it updating this PR to instead mention that (maybe in `README.md` in the examples directory?) would be amazing!

**Comment by nmyk** [comment]
Great! Thanks for your help. I'll update this PR to revert my change and instead update the `README.md` in the examples dir when I get a chance later :)

**Comment by Sean-Der** [comment]
:fire: glad to hear that helped!

Might also be worth adding a note to the main README.md, where ever you think it would be helpful. I am sure other people are hitting this issue, they just aren't filing an issue :(

**Comment by Sean-Der** [comment]
Merhed with a1bbddd0d86f820ff5052b5b93d75165eced07d1

Thank you so much @nmyk! Hopefully w/e you are building with Pion is going well.

**Pull request closed without merging**
