### PR TITLE
oggreader always fails if the input stream doesn't have data ready. 

### PR DESCRIPTION
**Pull request by kittuov**
#### Description
When tried to map a Reader which is not a file (stdout of subprocess) The oggreader always fails because it is expecting to read from a buffered input. 

In order to fix this, io.ReadFull is used like in ivfreader.

### CODE REVIEW

**Comment by Sean-Der** [comment]
Thanks for fixing this @kittuov, merging!

**Comment by Sean-Der** [comment]
Merged with 90121499393d122ee136d7c02774553043439b7d

Thank you so much for the contribution!

**Comment by at-wat** [comment]
@Sean-Der assert-contributors.sh seems failing on master

**Comment by Sean-Der** [comment]
@at-wat 👍 sorry my mistake, fixing in PR for remove CandidateSelectionTimeout!

**Pull request closed without merging**
