### PR TITLE
Mux: Wait and re-try writes (infinitely) when endpoint buffer is full

### PR DESCRIPTION
**Pull request by iamcalledrob**
#### Description
Mux will now wait and re-try writes (infinitely) when an endpoint's buffer is full.
Other code comments suggest that the buffer should never become full (see line 60 below), but that seems to not always be the case—and this is causing a race condition.
https://github.com/pion/webrtc/blob/655daa9689576421c194059dd4f3a05cae544a07/internal/mux/mux.go#L59-L62

This PR's approach may not be an ideal solution to the underlying problem, but as a band-aid it does appear to fix the issue.

This PR also updates the associated stress test to add CPU load while running, in order to trigger the bug outlined in https://github.com/pion/webrtc/issues/2152.
It's possible to verify this fix by merging only the updated test first—you'll see that quite often the test will stall with `mux ERROR: 2022/03/18 14:18:20 mux: ending readLoop dispatch error packetio.Buffer is full, discarding write` and eventually fail due to timeout.

#### Reference issue
Fixes https://github.com/pion/webrtc/issues/2152

### CODE REVIEW

**Comment by Sean-Der** [comment]
@iamcalledrob Thank you so much for diving deep on this! This is a great change. Might be worth doing a debug log?

So the issue is that `pion/dtls` and then `pion/sctp` aren't pulling buffers fast enough. This change instead will cause us to throw away incoming packets (which I think is better behavior)

Also worth benchmarking and figuring out where things are slowing down for you! If we see any obvious changes I would love to work on it together :)

@at-wat what do you think? Do you see any possible negative impacts?

**Comment by Sean-Der** [comment]
@iamcalledrob oh would you also mind deleting the note around SRTP? It isn't very helpful/misleading.

**Comment by at-wat** [comment]
If system can't handle packets fast enough and retry to process all packets and the condition continues, it will infinitely increase memory usage I guess.
I think it should be disabled by default to avoid decreasing DoS attack tolerance.

**Comment by iamcalledrob** [comment]
@at-wat I'm not sure that this would lead to infinite memory usage, but please correct me if I'm wrong here.

My understanding is that:
1. The kernel's socket receive buffer feeds into pion
2. Pion is currently able to read packets from the kernel faster than it can process them, leading to bug #2152. When this occurs it currently leads to undesirable behaviour—i.e. breaking out of the read loop.
3. This PR would have the effect of slowing down the speed that Pion reads from the socket receive buffer to match the speed that it's able to process the packets—essentially providing some back-pressure.
4. The kernel socket receive buffer is not unbounded, and if it becomes full then incoming UDP packets would get dropped by the kernel automatically.

Assuming this understanding is correct (big assumption!), this wouldn't lead to an increase in memory usage, since excess packets would be dropped rather than accumulating in a buffer somewhere.

@Sean-Der I will update the PR soon to remove the existing misleading comments :)

**Comment by Sean-Der** [comment]
@iamcalledrob Yes you are right! The incoming packets from `pion/ice` will just be dropped. If you turn on trace logging you should see this line being fired.

```
    if _, err := c.agent().buffer.Write(buffer); err != nil {
        log.Warnf("failed to write packet")
    }
```

* Would you also mind adjusting the tests so WASM can pass? Maybe just move that stress test into a file that is marked as non-WASM?
* Can you update the commit message. You can test that it passed the linter with `bash .github/lint-commit-message.sh` I would do something like

```
Wait and re-try when Mux destination ErrFull

Resolves #2152
```

* Fix linter error. You can get it by running `golangci-lint run`

```
 internal/mux/mux_test.go#L52

SA5004: should not have an empty default case in a for+select loop; the loop will spin (staticcheck)
```

**Comment by iamcalledrob** [comment]
@Sean-Der I've addressed the issues you outlined :) Linter and tests should be good-to-go.

Longer-term, a better solution might be for packetio.Buffer to offer a way to block writes until it has space for the write. Or return ErrFull but provide a mechanism to wait until the next Read occurs, so we can retry the write as soon as possible rather than polling every 20ms (a very arbitrary interval!).

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
Great work! I approved @iamcalledrob 

Totally agree with future improvements. Blocking sounds like a good idea to me, the only thing we need to watch out for is performance impact. packetio.Buffer is really easy to tweak and then negatively impact things :(

I added you to the Pion org, so hit that `Rebase and merge` button w/e you are ready :) 

You should also push a tag! `git tag v3.1.26 && git push --tags` after you have merged. Make sure you tag the commit in master. Hope you stay involved with Pion. Would love your help in pushing it to the next level re: performance of DataChannels.

**Pull request merged**
