### PR TITLE
Exmple h264,single direction -> camera to browser, stream app

### PR DESCRIPTION
**Pull request by dwoja22**
#### Description
An example demonstrating how to capture h264 stream via ffmpeg and stream it to browser via Pion WebRTC.

Signalling is done via websocket.

README.md contains instructions referencing the origin repo.
Please advise how to correct it.

Any other review comments are also welcome.

### CODE REVIEW

**Comment by at-wat** [comment]
@dwoja22 Thanks for your example!
We put the examples which use third party libraries in https://github.com/pion/example-webrtc-applications repository.
Could you move the PR to pion/example-webrtc-applications?

**Comment by Sean-Der** [comment]
Yea this is fantastic @dwoja22 we would really love to share your work :)

If you want you can also keep it under your own repo and put a link in [awesome-pion](https://github.com/pion/awesome-pion)

**Comment by dwoja22** [comment]
Hi,
I will move the PR to the correct place this weekend.
Will also fix, a few very small things I noticed before doing so.

**Comment by dwoja22** [comment]
PR moved to the correct repo
Closing this one

**Pull request closed without merging**
