### PR TITLE
Fix issue #1212 - Candidate with empty string

### PR DESCRIPTION
**Pull request by DevRockstarZ**
#### Description
I made the first test code by myself, it can be not perfect 😢
I tested on my local terminal, it passes all the cases.
I created test `PeerConnection` to use `AddICECandidate`, and I tested 3 test cases.
Thanks for reviewing!

#### Reference issue
Fixes [issue #1212](https://github.com/pion/webrtc/issues/1212)

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @DevRockstarZ this PR looks really good to me!

If you want to reopen I would love to merge this :) I will just squash your work into one commit. Really great work!

**Comment by DevRockstarZ** [comment]
@Sean-Der Thanks for your reply! I closed this PR due to you're working on this in Pion-V3.
I thought this PR will be bother you 😢
If re-open is fine, I will re-open it! Thanks!

**Comment by jsmouret** [comment]
Isn't it hiding the real issue?
https://github.com/pion/ice/issues/271

**Comment by DevRockstarZ** [comment]
@jsmouret 
I also think real issue is not cleared. 
So I did temporary fix to do not print errors from empty candidate.
I think real issue will be cleared when pion releases version 3.
Thanks!

**Comment by Sean-Der** [comment]
You are right @jsmouret thanks for keeping me honest :) 

So I think this is a two step process

* Update `pion/ice` to accept a `nil` candidate. [AddRemoteCandidate](https://github.com/pion/ice/blob/master/agent.go#L704) when called with `nil` should then set a field on the agent.

in the [contact](https://github.com/pion/ice/blob/master/agent.go#L494) loop it shouldn't go to failed unless this field has been set.

[restart](https://github.com/pion/ice/blob/master/agent.go#L1187) should update this field as well.

* then `pion/webrtc` should be updated to pass a `nil` candidate in.

This is a good amount of work, but I think there is a clear path forward! If anyone is interested in grabbing I can help :) the work done on the tests here is really great, I think we can use as is :)

**Comment by scorpionknifes** [comment]
Hey, @Sean-Der I'm reading into this and trying to clarify some stuff. (1st step ICE)

I'm reading into [5.6.3 RTCIceGathererState](https://www.w3.org/TR/webrtc/#rtcicegathererstate) and

complete | The RTCIceTransport has completed gathering and the end-of-candidates indication for this transport has been sent. It will not gather candidates again until an ICE restart causes it to restart.
--: | :--

I'm assuming the field on the agent that should be set is GatheringState by [agent.setGatheringState](https://github.com/pion/ice/blob/302290a7846159720a0feaa9d0d696f62ee7b50f/agent.go#L1214)

Since GatheringState is already reset in [agent.Restart](https://github.com/pion/ice/blob/302290a7846159720a0feaa9d0d696f62ee7b50f/agent.go#L1194) i think we don't need to update this field.

I'm also not too sure where to check this in contact loop.

**Comment by Sean-Der** [comment]
`ICEGatherState` is good, I don't believe we need to update that!

What we need to do is 

* Update the ICE Agent to not go to failed until it sees a `end-of-candidates` that check would go [here]( https://github.com/pion/ice/blob/master/agent.go#L498) 
* Update `pion/webrtc` to accept `nil` candidates, and send a `end-of-candidates` notification into `pion/ice`

**Comment by scorpionknifes** [comment]
@Sean-Der, need some advice

how do I store `end-of-candidate` attribute in ICE Agent?

since we sending nil to AddICECandidate do we want to pass nil to ICE or should we create a new func?

**Pull request closed without merging**
