### PR TITLE
Add vnet to SettingEngine

### LINKED ISSUE #778: Add vnet to SettingEngine
We should add the SettingEngine to the public API. This will allow users to simulate different network types, and it would be great for learning.

we should also make a bucket of examples to show people how it works!

### PR DESCRIPTION
**Pull request by Sean-Der**
Also add simple example to show usage

Resolves #778

### CODE REVIEW

**Comment by Sean-Der** [comment]
@enobufs I want to expand `vnet` a little bit more? 

What do you think would be the best API to show total inbound/outbound sent? I want to show how people can see the real world bandwidth cost of what they are building (and we can go from there)

thanks!

**Comment by enobufs** [comment]
@Sean-Der I can add that part.
Current vnet allows you to monitor packets that are traversing a vnet.Router using AddFilter() method on the router.

As all packets from both would show up on the filter, in order to track inbound/outbound a specific node (say, offerPeerConnection), I would fiter the packets by its IP address. 

Let me push my changes to the same branch for you to review later.

**Comment by enobufs** [comment]
Now it prints logs like this:
```
$ go run main.go
2019/12/07 22:42:18 inbound throughput : 1532.5 [Byte/s]
2019/12/07 22:42:18 outbound throughput: 1929.0 [Byte/s]
2019/12/07 22:42:20 inbound throughput : 737.5 [Byte/s]
2019/12/07 22:42:20 outbound throughput: 1138.0 [Byte/s]
2019/12/07 22:42:22 inbound throughput : 770.0 [Byte/s]
2019/12/07 22:42:22 outbound throughput: 1215.0 [Byte/s]
```

**Comment by Sean-Der** [comment]
That is amazing, thank you so much @enobufs! Didn't even think to use the ChunkFilter stuff.

Excited to land this, and see if maybe I can write a tweet about it and get people are interested :)

**Pull request merged**
