### PR TITLE
add drawio diagram for examples

### PR DESCRIPTION
**Pull request by mohammadne**
### progress

- [x] [broadcast](https://github.com/mohammadne/webrtc-pion/tree/master/examples/broadcast)
- [x] [custom-logger](https://github.com/mohammadne/webrtc-pion/tree/master/examples/custom-logger)
- [x] [data-channels](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels)
- [x] [data-channels-close](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels-close)
- [x] [data-channels-create](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels-create)
- [x] [data-channels-detach-create](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels-detach-create)
- [x] [data-channels-detach](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels-detach)
- [x] [data-channels-flow-control](https://github.com/mohammadne/webrtc-pion/tree/master/examples/data-channels-flow-control)
- [x] [ice-restart](https://github.com/mohammadne/webrtc-pion/tree/master/examples/ice-restart)
- [x] [ice-single-port](https://github.com/mohammadne/webrtc-pion/tree/master/examples/ice-single-port)
- [x] [ice-tcp](https://github.com/mohammadne/webrtc-pion/tree/master/examples/ice-tcp)
- [x] [insertable-streams](https://github.com/mohammadne/webrtc-pion/tree/master/examples/insertable-streams)
- [x] [ortc](https://github.com/mohammadne/webrtc-pion/tree/master/examples/ortc)
- [x] [pion-to-pion](https://github.com/mohammadne/webrtc-pion/tree/master/examples/pion-to-pion)
- [x] [play-from-disk-renegotation](https://github.com/mohammadne/webrtc-pion/tree/master/examples/play-from-disk-renegotation)
- [x] [play-from-disk](https://github.com/mohammadne/webrtc-pion/tree/master/examples/play-from-disk)
- [x] [reflect](https://github.com/mohammadne/webrtc-pion/tree/master/examples/reflect)
- [x] [rtp-forwarder](https://github.com/mohammadne/webrtc-pion/tree/master/examples/rtp-forwarder)
- [x] [rtp-to-webrtc](https://github.com/mohammadne/webrtc-pion/tree/master/examples/rtp-to-webrtc)
- [x] [save-to-disk](https://github.com/mohammadne/webrtc-pion/tree/master/examples/save-to-disk)
- [x] [simulcast](https://github.com/mohammadne/webrtc-pion/tree/master/examples/simulcast)
- [x] [swap-tracks](https://github.com/mohammadne/webrtc-pion/tree/master/examples/swap-tracks)
- [ ] [vnet](https://github.com/mohammadne/webrtc-pion/tree/master/examples/vnet)

#### notes

- on each example, press the `architecture` link to view online schema of the diagram

### CODE REVIEW

**Comment by mohammadne** [comment]
HI @Sean-Der 
I'm done.

can you please check it!
Thanks :)

**Comment by mohammadne** [comment]
@Sean-Der 

the only remaining diagram is for `vnet`, because currently I'm not vrey familiar with it,
I'll create another pull-request for that in the future (next week)

thanks for your awesome library :100:

**Comment by Sean-Der** [comment]
Fantastic work @mohammadne ! Thank you so much for contribution to Pion :)

I will review and merge first thing tomorrow. I think this will help people a lot.

**Comment by mohammadne** [comment]
Hi @Sean-Der 
is there any update on this pr ? 
thanks a lot for your fantastic work :)

**Comment by mohammadne** [comment]
Hi @Sean-Der 
Is there any update about status of this pr ?
thanks :)

**Comment by mohammadne** [comment]
HI @Sean-Der 
I have updated the branch to resolve the conflicts.
thanks

**Comment by Sean-Der** [comment]
Hi @mohammadne 

I really regret that this didn't get in. It was my fault that I didn't do a better job of guiding this PR. I am going to work on this.

Since this PR had started Github added mermaidjs. I started porting to mermaidjs [here](https://github.com/pion/webrtc/pull/2414). I put you as the author.

I started with data-channel, but I am planning on doing them all https://github.com/pion/webrtc/issues/2415. I understand if you are burned out/not interested in working on Pion (you didn't have a great experience). I would love to have you involved on this though!

**Pull request closed without merging**
