### PR TITLE
Remove duplicated options.Ordered check in peerconnection.go

### PR DESCRIPTION
**Pull request by AeroNotix**
#### Description
Removes duplicate code

### CODE REVIEW

**Comment by Sean-Der** [comment]
Nice catch @AeroNotix 

As soon as CI passes I will merge, thanks for the contribution!

**Comment by AeroNotix** [comment]
Not a problem! Thank you for making a high-quality, pure-Go WebRTC implementation!

**Comment by AeroNotix** [comment]
Removing code results in a _lower_ coverage score?

**Comment by Sean-Der** [comment]
Merged with b5fd3ead934b32611a3d1e86a0b60824d6b96506

Thanks again @AeroNotix, if you are interested in being involved further we would love to have you! I am on [Slack](https://pion.ly/slack) also if you have any questions, want to chat with the other devs

thanks :)

**Comment by AeroNotix** [comment]
Cheers! I'm writing a project with pion.webrtc so I'll be spending a bit of time in the codebase. If I find anything- I'll send a PR/issue.

Thanks again!

**Pull request closed without merging**
