### PR TITLE
Add examples/play-h264-from-disk

### PR DESCRIPTION
**Pull request by chertov**
#### Description
It doesn't work in Chrome. Only Firefox has been tested successfully.

### CODE REVIEW

**Comment by Esser420** [comment]
Also tried something similar with the RaspberryPi as it outputs raw h264. Also just worked for firefox and safari.

The only big differences I noticed are in the SDP generated by Chrome and the others. The one from chrome is much larger and detailed it seems, not sure the issue relies there though.

Looking at chrome://webrtc-internals it seems to be getting all the data, just drops all frames it receives. Might be something that pion is doing wrong internally

**Comment by Esser420** [comment]
I just checked this and it works on chrome on windows. I read somewhere that h264 on chrome on mac is not very well supported.

**Comment by Sean-Der** [comment]
Hey @chertov 

Sorry it took so long to review this, I have been really pulled into `/v3`. Would it be possible to rework this as a `H264Reader` ? This is a fantastic implementation, just hard to use since all the code is in the examples directory

When that is merged people will start being able to use it today! I also plan on making a `ffmpeg` example in `example-webrtc-applications` that shows how to use ffmpeg via stdin :)

thanks

**Comment by chertov** [comment]
@Sean-Der hi! Sorry for late answer!
I can try to move a h264 parsing code to https://github.com/pion/webrtc/tree/master/pkg/media/h264reader and add some tests for nal parsing process from my rust code. Will it be a good solution?

**Comment by Sean-Der** [comment]
@chertov yes that would be amazing!

It doesn't have to be perfect either. Happy to merge with some TODOs :)

**Comment by tarrencev** [comment]
@chertov just checking in here :) any chance you have bandwidth to make the suggested changes? would love to land this!

**Comment by ashellunts** [comment]
Hello, I have tried to run the example. I have following output:
```
Connection State has changed checking
<SDP here>
Connection State has changed failed

```
How can I debug this? Are there log files?

**Comment by Sean-Der** [comment]
Closing for #1502 thanks for starting this @chertov !

**Pull request closed without merging**
