### PR TITLE
Run ops.GracefulClose earlier in pc.Close

### PR DESCRIPTION
**Pull request by edaniels**
Without this, it increases the chance of races between resources a PeerConnection owns and operations on the ops queue that affect those resources. For example, a SetRemoteDescription that opens an SCTP stream for a data channel could be running while we close down the peer connection. If there were a bug in the SCTP library that incorrectly performs operations after close, this would be an issue (like in https://github.com/pion/sctp/pull/348).

### CODE REVIEW

**Review by sukunrt — APPROVED** [review]
I am not too sure of this change. It looks like a stopgap measure where ideally we should be moving all the code in peerconnection.go that does
```
pc.sctpTransport.lock.Lock()
...
pc.sctpTransport.lock.Unlock()
```
into sctpTransport and let that object handle the correctness of operations after close. 

However, I'm sure it doesn't make anything worse, so it's okay from my side to merge.

Note: we cannot gracefully close `datachannels` once `sctpTransport.Stop` has been called.

**Comment by edaniels** [comment]
> I am not too sure of this change. It looks like a stopgap measure where ideally we should be moving all the code in peerconnection.go that does
> 
> ```
> pc.sctpTransport.lock.Lock()
> ...
> pc.sctpTransport.lock.Unlock()
> ```
> 
> into sctpTransport and let that object handle the correctness of operations after close.
> 
> However, I'm sure it doesn't make anything worse, so it's okay from my side to merge.
> 
> Note: we cannot gracefully close `datachannels` once `sctpTransport.Stop` has been called.

Why can't they be gracefully closed at that point?

**Comment by edaniels** [comment]
> I am not too sure of this change. It looks like a stopgap measure where ideally we should be moving all the code in peerconnection.go that does
> 
> ```
> pc.sctpTransport.lock.Lock()
> ...
> pc.sctpTransport.lock.Unlock()
> ```
> 
> into sctpTransport and let that object handle the correctness of operations after close.
> 

Also I agree but it's a larger change and a little bit more invasive to existing behavior. I'll file an issue!

> However, I'm sure it doesn't make anything worse, so it's okay from my side to merge.
> 
> Note: we cannot gracefully close `datachannels` once `sctpTransport.Stop` has been called.

**Comment by sukunrt** [comment]
>Why can't they be gracefully closed at that point?

I think I was wrong here. Gracefully closing the datachannel will wait for the readloop to complete, which I guess is the point of graceful close.

**Comment by edaniels** [comment]
Reverted this. There wasn't an accompanying test that would show this fails easily in a race to start and stop ops. Op queue has no way of canceling in progress ops.

**Pull request merged**
