### PR TITLE
Pass all fingerprints from SDP to dtls transport

### PR DESCRIPTION
**Pull request by suhasgaddam**
Before pion was only checking against the first fingerprint found in
the SDP, now all fingerprints from the SDP are used to validate
during the dtls handshake.

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by Sean-Der** [comment]
@suhasgaddam 

Here is the text from the RFC
```
   The fingerprint attribute may be either a session-level or a media-
   level SDP attribute.  If it is a session-level attribute, it applies
   to all TLS sessions for which no media-level fingerprint attribute is
   defined.
```

So it sounds like we need to ignore the session level attribute, for each of the individual ones. I *think* this is the proper logic then.

* Loop through each media sections. If you find a fingerprint use it, confirm that all the fingerprints match though. Currently we only support one `DTLSTransport`, so that is an important error to communicate to the user.
* If we didn't find anything at the media level, then check the session level. If there isn't anything at the session level return an error.

Sorry I didn't respond sooner!

**Comment by Sean-Der** [comment]
@suhasgaddam hey! no rush, but anything I can do to help here?

Hopefully you are still using Pion for your project. If not I am happy to write/land this change myself, but would much rather see contributors :)

thanks (and no rush!)

**Comment by suhasgaddam** [comment]
@Sean-Der, I am still using pion. The current changeset was a quick and dirty fix for me(and I didn't know what should happen if there are multiple fingerprints). I can still fix this up according to the RFC, as long as no one is in a rush for the fix.

**Comment by suhasgaddam** [comment]
I still need to test this against an actual application. What should happen if N media sections, 1 section does not have a fingerprint?

**Comment by Sean-Der** [comment]
> I still need to test this against an actual application. What should happen if N media sections, 1 section does not have a fingerprint?

It should use the session fingerprint.

If the session doesn't match the other Media fingerprints then we need to error out. In the future we can support multiple fingerprints (multiple DTLS sessions) but for the time being we just support one DTLSTransport.

**Comment by Sean-Der** [comment]
No rush either! I think this is a great fix (and I am sure people are hitting this today) so will be great to get in :)

**Comment by Sean-Der** [comment]
Closing for #1023

**Pull request closed without merging**
