### PR TITLE
Update nack interceptor

### PR DESCRIPTION
**Pull request by tarrencev**
Generate + Respond interceptors

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by Sean-Der** [comment]
@tarrencev mind just leaving this as a branch (for now)  When we merge that branch in pion/interceptor we will lose the SHA. Just so we don't have un-buildable commits.

@at-wat mind looking at pion/interceptor NACK PR? Happy to wait if you need a few days! If you don't have the time we can just merge and come back to it later, thanks!

**Comment by tarrencev** [comment]
@Sean-Der yup! was just opening this so it is ready once we land the rest :)

**Comment by Sean-Der** [comment]
@tarrencev I haven't had a chance to test this yet, but here it is :)

I am gonna confirm they are being emitted/are valid tomorrow!

**Comment by Sean-Der** [comment]
@tarrencev This is all good to go :) 

Is everyone ok with this being on by default? We can improve the implementation as we go. 

One thing is we know require people to process RTCP, so I updated all the relevant examples. It might be worth revisiting interceptors. I saw that @robin-raymond may have had design concerns with it as well.

**Review by Sean-Der — APPROVED** [review]

**Comment by tarrencev** [comment]
awesome! lets merge whenever you're ready!

**Comment by Sean-Der** [comment]
done :)

**Pull request merged**
