### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by mr-shitij**
Changes :

1. Use the recommended replacements for io/ioutil functions
2. Fix superfluous else statements
3. Fix check for empty string

### CODE REVIEW

**Comment by Sean-Der** [comment]
Great fixes @mr-shitij thank you so much for improving the code :) 

I am merging now and adding you to the `CONTRIBUTORS` file.

**Comment by Sean-Der** [comment]
Merged with 789623a7f745db6816625730ac61c17cfe4b3117

**Comment by mr-shitij** [comment]
Thank You ..!!

**Comment by Sean-Der** [comment]
Of course!

If you are interested in contributing more to Pion we would love to have you @mr-shitij 

Lots of issues that need help. I am also on [Pion Slack](https://pion.ly/slack) if you want guidance/ideas on what to work on

**Comment by mr-shitij** [comment]
Yes Sir, I am very excited to work ..!!

**Pull request closed without merging**
