### PR TITLE
Add test to check whether the samplebuilder drops data

### PR DESCRIPTION
**Pull request by jech**
This test is successful with v3.0.27.  In v3.0.31, it reports large numbers of dropped packets.

Related to #1839 and #1870.

### CODE REVIEW

**Comment by robin-raymond** [comment]
There's an issue with this test. The buffers will hold back because it cannot tell if the first packet in the sequence is truly the first packet. Only once the packet count holdback is exceeded then the packets will release (and there will always be a hold back until the end because there's no 'flush' mechanism to say EOF on the stream).

**Comment by jech** [comment]
That's what the partitionHeadChecker is for.

**Comment by robin-raymond** [comment]
Just because it's the first packet that arrived is a partition head doesn't mean there isn't a packet that might arrive later / in front of the current head that is also a head. Every audio sample is a "head" for example.

**Comment by robin-raymond** [comment]
I added your test and made it pass. The issue is during the wrap around which someone else reported not consistently retaining a backlog of packets. You can cancel this PR.

**Comment by Sean-Der** [comment]
That's great news! Thanks @robin-raymond :)

**Pull request closed without merging**
